apiVersion: v1
kind: Pod
metadata:
 name: webserver3
 labels:
  app: myapp3
spec:
 containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
 initContainers:
  - name: sleep
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c' , 'sleep 100'] 
