apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
 namespace: default
 name: pod-deployment
rules:
 - apiGroups: ["apps"]
   resources: ["deployments"]
   verbs: ["get","list","watch"]
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "watch","list"]

