apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payappdeployment
  name: payappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payappdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payappdeployment
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: IfNotPresent
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payappdeployment
  name: payappdeployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: payappdeployment
  type: NodePort
status:
  loadBalancer: {}
