apiVersion: v1
kind: Pod
metadata:
 name: liveness1-example3 
 labels:
   app: liveness3

spec:
 containers:
  - name: liveness3
    image:  k8s.gcr.io/liveness
    args:
     - /server
    imagePullPolicy: IfNotPresent

    livenessProbe:
     tcpSocket:
      port: 8080
     periodSeconds: 5
     initialDelaySeconds: 5
