apiVersion: v1
kind: Pod
metadata:
 name: readiness-example1 
 labels:
   app: liveness1

spec:
 containers:
  - name: readiness1
    image:  nginx:latest
    imagePullPolicy: IfNotPresent
    readinessProbe:
     exec:
      command:
       - cat
       - /tmp/health
     periodSeconds: 5
     initialDelaySeconds: 5
