apiVersion: v1
kind: Pod
metadata:
 name: liveness1-example2 
 labels:
   app: liveness1

spec:
 containers:
  - name: liveness1
    image:  k8s.gcr.io/liveness
    args:
     - /server
    imagePullPolicy: IfNotPresent

    livenessProbe:
     httpGet:
      path: /healthz
      port: 8080
      httpHeaders:
       - name: Custom-Header
         value: Awesome
     periodSeconds: 5
     initialDelaySeconds: 5
