apiVersion: v1
kind: Pod
metadata:
 name: resource-example3 
 labels:
   app: resource

spec:
 containers:
  - name: stress-example
    image:  polinux/stress
    imagePullPolicy: IfNotPresent
    command: ["stress"]
    args: ["--vm" , "1", "--vm-bytes" , "250M" , "--vm-hang" ,"1"]
    resources:
     requests:
      memory: "100Mi"
     limits:
      memory: "200Mi"
