apiVersion: v1
kind: Pod
metadata:
 name: liveness1-example1 
 labels:
   app: liveness1

spec:
 containers:
  - name: liveness1
    image:  nginx:latest
    imagePullPolicy: IfNotPresent

    livenessProbe:
     exec:
       command:
         - cat
         - /var/run/nginx.pid
     periodSeconds: 5
     initialDelaySeconds: 5
