apiVersion: v1
kind: Pod
metadata:
 name: sidebar
 labels:
   app: sidecar-app

spec:
 volumes:
  - name: logs
    emptyDir: {}

 containers:
  - name: app-container
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c" , "while true; do date > /var/log/index.html ; sleep 1 ; done "]
    volumeMounts:
      - name: logs
        mountPath: /var/log

  - name: log-exporter
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports: 
     - containerPort: 80
    volumeMounts:
      - name: logs
        mountPath: /usr/share/nginx/html/



