apiVersion: v1
kind: PersistentVolume
metadata:
 name: examplepv1
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 storageClassName: nfs
 mountOptions:
  - hard
  - nfsvers:4.1
 nfs:
  path: /var/nfs_share
  server: 192.168.21.104
