apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          imagePullPolicy: IfNotPresent
          env:
           - name: username
             valueFrom:
              secretKeyRef:
               name: mysecret1
               key: username
           - name: username
             valueFrom:
              secretKeyRef:
               name: mysecret1
               key: username
               
