apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxdeployment1
  name: nginxdeployment1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdeployment1
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxdeployment1
  name: nginxdeployment1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdeployment1
  type: ClusterIP
status:
  loadBalancer: {}
