apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
       - name: nginx-content
         persistentVolumeClaim:
          claimName: examplepvc2
      containers:
      - image: nginx:latest
        name: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: nginx-content
           mountPath: /usr/share/nginx/html
