apiVersion: v1
kind: PersistentVolume
metadata:
 name: examplepv2
spec:
 storageClassName: manual
 capacity: 
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/var/kubernetes_log" 

