apiVersion: v1
kind: PersistentVolume
metadata:
 name: examplev1
spec:
 capacity: 
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 storageClassName: nfs
 mountOptions:
  - hard
  - nfsvers=4.1
 nfs:
  path: /var/nfs_folder
  server: 192.168.21.104 
