apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
       - name: nginx-config
         configMap:
           name: nginxconfig
      containers:
        - image: nginx:latest
          name: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
           - name:  nginx-config
             mountPath: /etc/nginx/conf.d/default.conf
             subPath: default.conf
             readOnly: true
        
